name: build

on: workflow_call
# on:
#     push:
#     branches: ['main']
#     paths: ['api/**','unit-testing/**','.github/workflows/**', 'compose.*.yaml']
jobs:
  call-test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  call-version:
    needs: [call-test]
    uses: ./.github/workflows/version.yml
    secrets: inherit
  call-publish:
    needs: [call-version]
    uses: ./.github/workflows/publishbuild.yml
    secrets: inherit
  call-deploy:
    needs: [call-publish]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
  