name: publish build

on: workflow_call
    
jobs:
  publish_images:
      runs-on: ubuntu-latest
      steps:
          - name: checkout
            uses: actions/checkout@v4.1.7
          - name: checkout
            uses: actions/checkout@v4.1.7
            with:
              fetch-depth: 0
          - name: Get Previous tag
            id: previoustag
            uses: "WyriHaximus/github-action-get-previous-tag@v1"
            with:
              fallback: v1.0.0 # Optional fallback tag to use when no tag can be found
          - run: echo $"${{steps.previoustag.outputs.tag}}"
          - name: login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: build and publish api
            run: |
              docker build ./api/ -t poi9912/agriculture-api:latest --push
              docker build ./api/ -t poi9912/agriculture-api:${{steps.previoustag.outputs.tag}} --push
          - name: build and publish mock-importer
            run: |
              docker build ./mocks/ -t poi9912/agriculture-mock-importer:latest --push
              docker build ./mocks/ -t poi9912/agriculture-mock-importer:${{steps.previoustag.outputs.tag}} --push